# Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
for i in a:
    print(i)

1
2
3
4
5


### Broadcasting

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
# hard work
for i in range(len(a)):
   a[i] = a[i]+5

In [ ]:
a

array([ 6,  7,  8,  9, 10])

In [ ]:
b = np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = b+5
b

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
b = b-10
b

array([-4, -3, -2, -1,  0,  1])

In [ ]:
a = list(range(1, 11))
a, type(a)

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], list)

In [ ]:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = a**2
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
a = a/10
a

array([ 0.1,  0.4,  0.9,  1.6,  2.5,  3.6,  4.9,  6.4,  8.1, 10. ])

In [ ]:
a = a*2
a

array([ 0.2,  0.8,  1.8,  3.2,  5. ,  7.2,  9.8, 12.8, 16.2, 20. ])

### Operation

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([4, 5, 6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
b-a

array([3, 3, 3])

In [ ]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [ ]:
b**a

array([  4,  25, 216])

In [ ]:
6**3

216

In [ ]:
a*b

array([ 4, 10, 18])

## Functions

In [ ]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.shape

(4,)

In [ ]:
a.shape

(3, 4)

In [ ]:
a = np.zeros((3,4), dtype = int)

In [ ]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a = np.ones((4,4), dtype = int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a = np.eye(5, dtype= 'int')

In [ ]:
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
a = np.zeros((3,3), dtype = 'int')
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = a+5
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
b = np.ones((3,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
b = b+4 # b = b*5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
a = np.ones((3,3,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a.shape

(3, 3, 3)

In [ ]:
a = np.array([[2,7], [4,5]])
a

array([[2, 7],
       [4, 5]])

In [ ]:
a.shape

(2, 2)

In [ ]:
a.min()

2

In [ ]:
a.min(axis = 0) # axis 0 is for rows

array([2, 5])

In [ ]:
a.min(axis = 1) # axis 1 is for col

array([2, 4])

In [ ]:
a.max()

7

In [ ]:
a.max(axis = 0)

array([4, 7])

In [ ]:
a

array([[2, 7],
       [4, 5]])

In [ ]:
a.max(axis = 1)

array([7, 5])

In [ ]:
a.mean()

4.5

In [ ]:
a.mean(axis=0)

array([3., 6.])

In [ ]:
a.mean(axis=1)

array([4.5, 4.5])

In [ ]:
a.std()

1.8027756377319946

In [ ]:
np.median(a)

4.5

# Random Numbers

In [ ]:
np.random.randint(1, 10)

7

In [ ]:
for i in range(10):
    print(np.random.randint(1, 10))

7
6
6
1
5
3
9
5
4
8


In [ ]:
a = np.random.randint(1, 10, (4,3))
a

array([[4, 4, 3],
       [9, 1, 6],
       [7, 1, 9],
       [9, 1, 9]])

In [ ]:
a.shape

(4, 3)